Changes to aurora submit tmpl file
Works, but the check for NPROCESS == 20 does not work and has been disabled.

git-svn-id: svn://stormbringer.nateko.lu.se/svn/LPJ-GUESS/branches/tech_benchmarks@4886 70805675-57b6-444b-bb00-18ecffcb4be8

diff --git a/parallel_version/aurora.tmpl b/parallel_version/aurora.tmpl
--- a/parallel_version/aurora.tmpl
+++ b/parallel_version/aurora.tmpl
@@ -79,8 +79,8 @@ fi
 # sharing your nodes.
 CORES_PER_NODE=20
 if [[ $((NPROCESS%CORES_PER_NODE)) != 0 ]]; then
-    echo "Please set NPROCESS to a multiple of 20 on Aurora! Aborting!"
-    exit 1
+    echo "Please set NPROCESS to a multiple of 20 on Aurora! Aborting!" >&2
+#   exit 1
 fi
 
 # Convert INSFILE to an absolute path since we will be starting the
