The benchmarks script now has an option for running only the post processing.
git-svn-id: svn://stormbringer.nateko.lu.se/svn/LPJ-GUESS/branches/benchmark_improvements@371 70805675-57b6-444b-bb00-18ecffcb4be8

diff --git a/benchmarks/benchmarks b/benchmarks/benchmarks
--- a/benchmarks/benchmarks
+++ b/benchmarks/benchmarks
@@ -29,6 +29,7 @@ function print_usage_and_exit {
     error "======="
     error "-s   Single machine mode, don't use PBS"
     error "-c   Compile only, don't run the tests"
+    error "-p   Post processing only"
     error "-i   Include only the specified tests"
     error "-x   Exclude the specified tests"
     error
@@ -60,9 +61,10 @@ function includes {
 
 single_machine=0
 compile_only=0
+pp_only=0
 
 # Handle the -s, -c, -i and -x options
-while getopts ":sci:x:" opt; do
+while getopts ":scpi:x:" opt; do
     case $opt in
 	i  ) inclusive=$OPTARG
 	     inclusive_flag=1 ;;
@@ -70,6 +72,7 @@ while getopts ":sci:x:" opt; do
 	     exclusive_flag=1 ;;
 	s  ) single_machine=1 ;;
 	c  ) compile_only=1 ;;
+	p  ) pp_only=1 ;;
 	\? ) print_usage_and_exit ;;
     esac
 done
@@ -85,6 +88,11 @@ if (( $single_machine == 0 )); then
 	error "benchmarks on the local machine with the -s option."
 	exit 1
     fi
+fi
+
+if (( $compile_only == 1 && pp_only == 1 )); then
+    error "-c and -p can't be used at the same time!"
+    exit 1
 fi
 
 # Throw away the options getopts handled
@@ -166,6 +174,39 @@ function setup_workspace {
     fi
 }
 
+# This function submits the post processing job.
+# Parameters:
+# $1  The name of the benchmark
+# $2  Job-id of the actual benchmark job (for dependency)
+#     Don't supply if running only the post processing
+function submit_pp {
+    local test_name=$1
+    local workspace=$work_dir/$test_name
+    local bm_root=$PWD
+
+    # Construct argument for qsub for dependency if there is one
+    if [ -n "$2" ]; then
+	dependency="-W depend=afterok:$jobid"
+    else
+	dependency=""
+    fi
+
+    pushd $workspace &> /dev/null
+    # Create the post processing job
+    qsub -l walltime=5:00:00 $dependency <<EOF &> /dev/null
+#!/bin/sh
+#PBS -N bm_${test_name}_pp
+cd $workspace
+if [ -f $bm_root/$test_name/postprocess.sh ]; then
+    PATH=$bm_root/postprocess:$PATH sh $bm_root/$test_name/postprocess.sh
+fi
+ls | grep "^run[0-9]*$" | xargs rm -rf
+cd $bm_root
+echo '$test_name' >> progress.txt
+EOF
+    popd &> /dev/null    
+}
+
 # This function submits a benchmark as a PBS job
 # Parameters:
 # $1  The name of the benchmark
@@ -182,23 +223,32 @@ function submit_job {
     else
 	jobid=$(sh submit.sh -i $insfile -n "bm_$test_name" 2> /dev/null)
     fi
+    popd &> /dev/null
+
     if (($? != 0)); then
 	error "Failed to submit $test_name!"
     else
-	# Create the post processing job
-	qsub -l walltime=5:00:00 -W depend=afterok:$jobid <<EOF &> /dev/null
-#!/bin/sh
-#PBS -N bm_${test_name}_pp
-cd $workspace
-if [ -f $bm_root/$test_name/postprocess.sh ]; then
-    PATH=$bm_root/postprocess:$PATH sh $bm_root/$test_name/postprocess.sh
-fi
-ls | grep "^run[0-9]*$" | xargs rm -rf
-cd $bm_root
-echo '$test_name' >> progress.txt
-EOF
+	submit_pp $test_name $jobid
     fi
+}
+
+# This function runs the post processing as a regular process
+# (not using PBS)
+# Parameters:
+# $1 The name of the benchmark
+function run_single_machine_pp {
+    local test_name=$1
+    local workspace=$work_dir/$test_name
+    local bm_root=$PWD
+
+    pushd $workspace &> /dev/null
+    if [ -f $bm_root/$test_name/postprocess.sh ]; then
+	PATH=$bm_root/postprocess:$PATH nice sh $bm_root/$test_name/postprocess.sh
+    fi
+    ls | grep "^run[0-9]*$" | xargs rm -rf
     popd &> /dev/null
+
+    echo $test_name >> $bm_root/progress.txt
 }
 
 # This function runs a benchmark as a regular process
@@ -212,17 +262,14 @@ function run_single_machine_model {
 
     pushd $workspace &> /dev/null
     nice ./guess $bm_root/$test_name/config/guess.ins
-    if [ -f $bm_root/$test_name/postprocess.sh ]; then
-	PATH=$bm_root/postprocess:$PATH nice sh $bm_root/$test_name/postprocess.sh
-    fi
-    ls | grep "^run[0-9]*$" | xargs rm -rf
     popd &> /dev/null
-    echo $test_name >> $bm_root/progress.txt
+
+    run_single_machine_pp $test_name
 }
 
 # This function takes care of everything that needs to be done 
-# for a benchmark: building, setting up the workspace and
-# submitting the job.
+# for a benchmark: building, setting up the workspace,
+# submitting the model job and submitting the post processing job.
 # Parameters:
 # $1  The test name
 function run_benchmark {
@@ -250,6 +297,24 @@ function run_benchmark {
     fi
 }
 
+# This function runs just the post processing for one benchmark.
+# Parameters:
+# $1 The test name
+function run_pp {
+    local test_name=$1
+    local workspace=$work_dir/$test_name
+
+    if [ -d $workspace ]; then
+	if (( $single_machine == 1 )); then
+	    run_single_machine_pp $test_name
+	else
+	    submit_pp $test_name
+	fi
+    else
+	echo "$workspace doesn't exist, skipping!"
+    fi
+}
+
 # Ok, let's start!
 
 # Create the progress.txt file, overwriting if it existed
@@ -263,9 +328,12 @@ mkdir -p $work_dir
 work_dir=`cd $1; pwd`
 
 # Build the model which will be used by benchmarks that don't have their own
-# special code.
-echo "Building standard model..."
-build $work_dir/standard_build
+# special code. No need to build it if we're only doing post processing
+# however.
+if (( $pp_only == 0 )); then
+    echo "Building standard model..."
+    build $work_dir/standard_build
+fi
 
 # Find all sub directories
 subdirs=($(find . -mindepth 1 -maxdepth 1 -type d))
@@ -299,7 +367,11 @@ done
 # Call run_benchmark for each test
 for test_name in "${test_names[@]}"
 do
-  run_benchmark $test_name
+  if (( $pp_only == 1 )); then
+      run_pp $test_name
+  else
+      run_benchmark $test_name
+  fi
 done
 
 if (( $compile_only == 1 )); then
