Replaced the Simba submit script and changed how guess is run on Simba.
The new submit script takes care of the parallelism, splitting gridlist, 
appending etc. by itself. This means we can use the regular commandline version
of guess (no need for an MPI version).

The new submit script is generated from an M4 template (makes it easier to
read and modify).


git-svn-id: svn://stormbringer.nateko.lu.se/svn/LPJ-GUESS/branches/guess2008@51 70805675-57b6-444b-bb00-18ecffcb4be8

diff --git a/benchmarks/benchmarks b/benchmarks/benchmarks
--- a/benchmarks/benchmarks
+++ b/benchmarks/benchmarks
@@ -103,11 +103,6 @@ work_dir=$1
 function build {
     local build_path=$1
     local additional_source=$2
-    local target=""
-
-    if (( $single_machine == 0 )); then
-	target="pbs"
-    fi
 
     echo "Building in $build_path"
 
@@ -125,18 +120,18 @@ function build {
     fi
 
     pushd $build_path &> /dev/null
-    if ! $make_command $target &> /dev/null ; then
+    if ! $make_command &> /dev/null ; then
 	error "Failed to build " $build_path "!"
 	exit 1
     fi
-    popd &> /dev/null
-    
+
     if (( $single_machine == 0 )); then
-	cp makescript $build_path
-	mv $build_path/output/guess_pbs $build_path/guess
-    else
-	mv $build_path/output/guess $build_path/guess
+	if ! $make_command pbs &> /dev/null ; then
+	    error "Failed to generate submit script!"
+	    exit 1
+	fi
     fi
+    popd &> /dev/null
 }
 
 # This function prepares the workspace for one of the benchmarks
@@ -149,26 +144,21 @@ function setup_workspace {
     local build_path=$2
 
     local workspace=$work_dir/$test_name
-    local submit_vars=$PWD/$test_name/submit_vars.sh
 
     rm -rf $workspace
     mkdir $workspace
 
     if (( $single_machine == 1 )); then
-	ln -s $build_path/guess $workspace/guess
+	ln -s $build_path/output/guess $workspace/guess
     else
-        # Create the submit script
-	pushd $build_path &> /dev/null
-	if [ -f $submit_vars ]; then
-	    sh makescript guess $workspace/submit.sh $submit_vars
-	else
-	    sh makescript guess $workspace/submit.sh
-	fi
-	popd &> /dev/null
+        # Get the submit script
+	cp $build_path/output/submit.sh $workspace
     fi
 
     # Copy the config files to the workspace
     cp $test_name/config/* $workspace
+
+    # Limit the gridlist if there is a boundingbox.txt
     if [ -f $test_name/config/boundingbox.txt ]; then
 	bbox=$(cat $test_name/config/boundingbox.txt)
 	$bbox_command -f $test_name/config/gridlist.txt \
@@ -183,9 +173,14 @@ function submit_job {
     local test_name=$1
     local workspace=$work_dir/$test_name
     local bm_root=$PWD
+    local submit_vars=$PWD/$test_name/submit_vars.sh
 
     pushd $workspace &> /dev/null
-    jobid=$(sh submit.sh "bm_$test_name" 2> /dev/null)
+    if [ -f $submit_vars ]; then
+	jobid=$(sh submit.sh -n "bm_$test_name" -s $submit_vars 2> /dev/null)
+    else
+	jobid=$(sh submit.sh -n "bm_$test_name" 2> /dev/null)
+    fi
     if (($? != 0)); then
 	error "Failed to submit $test_name!"
     else
