Now also pyhton for report2html works. Todo: fix printerfriendly: python2 and ev. also module load.
And also clean upp the code at the end of runposprocess.


git-svn-id: svn://stormbringer.nateko.lu.se/svn/LPJ-GUESS/branches/tech_clustr@13096 70805675-57b6-444b-bb00-18ecffcb4be8

diff --git a/benchmarks/runpostprocessing b/benchmarks/runpostprocessing
--- a/benchmarks/runpostprocessing
+++ b/benchmarks/runpostprocessing
@@ -125,4 +125,16 @@ print_report_footer
 
 # Convert the XML file to HTML
 cd report
-$(dirname $0)/report2html report.xml ../../info.txt > index.html
+
+if [[ "$ARCH" == "lunarc" || "$ARCH" == "aurora" ]]; then
+  module load Python/2.7.18	# Load the correct Python 2 module
+fi
+python2_path=$(which python2)	# Ensure Python 2 is used
+if [ -z "$python2_path" ]; then
+    echo "Error in runpostprocessing: Python 2 not found!"
+    exit 1
+fi
+which python	# debug
+python -V	# debug
+
+$python2_path $(dirname $0)/report2html report.xml ../../info.txt > index.html		# This script needs to be run by python2
